### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by Apehaenger**
Not very nice, but haven't found a better/cheaper way to integrate generic string translations of displayed text.

~~Take a note that this patch has my previous PlatformIO patch included, as I work with PlatformIO. I can split them up if you're not comfortable with it.~~

### CODE REVIEW

**Comment by wuspy** [comment]
I'm experimenting with adding unicode support to this project so we don't have to latinize non-english text. The fonts it uses have support for all windows-1252 characters anyway. But the way you've handled the translations is fine and that's how I would've done it too, so I'll probably use this PR as a branch commit unicode changes under if I can get it working.

**Comment by wuspy** [comment]
I'm assuming you speak german, so can you confirm if 'MAERZ' is just the latinized version of 'MÄRZ' and that the latter would be more appropriate? I don't want to make assumptions based on translations I found online.

**Comment by Apehaenger** [comment]
> ... the way you've handled the translations is fine and that's how I would've done it too

If you plan to merge LordNed's awesome [WiFi Manager PR](https://github.com/wuspy/portal_calendar/pull/11), then the translations need to be moved from the preprocessor into run-time space (so that the language can be selected during setup) and we probably should use a real (but small) localization lib?!

A quick look resulted in:
- [GNU Gettext](https://www.gnu.org/software/gettext/) which look heavily overkill to me (and not available for arduino framework?!)
- [Boost.Locale](https://www.boost.org/doc/libs/1_58_0/libs/locale/doc/html/index.html) has pretty simple [message formatting](https://www.boost.org/doc/libs/1_58_0/libs/locale/doc/html/messages_formatting.html) capabilities, but it still depend on the [GNU Gettext](https://www.gnu.org/software/gettext/) tools :-/ ... so still overkill for a handful of translation strings?

Or should we stay dump simple and give i.e. ```const char *MONTHS[] = {...``` (and the like/relevant) from Display.cpp a second language dimension? And probably move them into a separate file (localization.h or Display_locale.h) so that we don't make the cpp file unreadable?

Any suggestion on this?

> ... can you confirm if 'MAERZ' is just the latinized version of 'MÄRZ' ...

Yes! 'MÄRZ' is much more appreciate!!

An for the case that you didn't stumbled about it till now: AFAIR there's no real rule, but in my personal opinion, the 3-char day abbreviations are also uncommon for German. I tested the 3-char ones and I guess every German speaking will understand what's meant with "MON", "DIE", "MIT", ... but they looked weird to me ;-), whereas we've had "Mo Di Mi ..." songs in school

**Comment by wuspy** [comment]
I agree that gettext is overkill, and so far I haven't found a c++ translation library that looks like it would work well. I did some refactoring (just moving the days/months/abbreviations arrays to localization.h directly) and I plan on keeping it that way for the time being. I don't know if this is going to scale well for translating the setup page in #11, but it could be a while before that PR is fully tested and merged and having the days and months translated + UTF8 support is a lot better than no localization at all. The calendar also currently shows their WiFi SSID and location name on the screen in case of error, so proper UTF8 support and handling of replacement characters will fix existing display issues with those.

Also I have no idea what WifiManager is even doing with their localization. [Look at this](https://github.com/tzapu/WiFiManager/blob/master/wm_strings_en.h). Why is there javascript in the localization file? Why are there entire HTML layouts and CSS in the localization file? Do they intend for me to write the entire webpage from scratch if I'm adding a new locale? That project has 70 contributors and 5.7k stars so they should know what they're doing, but from the perspective of a professional web developer this looks absolutely insane. So yeah, there's a lot to figure out concerning #11 and localization.

**Comment by Apehaenger** [comment]
Quite thanks for the merge!

> ... I did some refactoring (just moving the days/months/abbreviations arrays to localization.h directly) and I plan on keeping it that way for the time being. I don't know if this is going to scale well for translating the setup page in #11, but it could be a while before that PR is fully tested and merged and having the days and months translated + UTF8 support is a lot better than no localization at all. The calendar also currently shows their WiFi SSID and location name on the screen in case of error, so proper UTF8 support and handling of replacement characters will fix existing display issues with those.

Yes, thanks, but against my initial thought I get more and more the impression that the language should be choosen at compile time because:
- You know for whom you build/make the calendar. A language switch on user side feels somehow overkill (over-engineered)
- Simplifies code
- Save resources and a lot space

**Comment by wuspy** [comment]
Yeah that was the same conclusion I came to. With WifiManager we still need to decide on a language for the setup instructions shown on the screen so it needs to be chosen at compile time. And without WifiManager everything is configured at compile time.

**Pull request merged**
