### PR TITLE
Use WiFiManager to manage Credentials and User Preferences

### LINKED ISSUE #7: Avoiding Hardcoding WiFi Credentials
Neat project. I'd like to give one as a gift but teaching friends how to compile and flash an ESP32 might be a bit too much of a gift. I was looking at potentially forking and integrating a wifi manager where, if wifi connection fails, it boots up into access point mode so you can connect to it via your phone and enter wifi credentials, and then have them saved on the device.

Looking around it looks like there's a package for the ESP32 by user Tzapu - https://github.com/tzapu/WiFiManager. Is this something you're interested in taking a pull request to add? If so, do you have thoughts on how you would want it implemented. I can make an effort to implement it that way to make it easier to take back as a PR.

My initial thoughts were to just set up a new set of defines in the header, instead of:

`#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi password here"`

Have something like
```
#define USE_ACCESS_POINT_CONFIG 1
#if USE_ACCESS_POINT_CONFIG
// IP Address the device will create a webserver on to config
#define WIFI_ACCESSPOINT_NAME "Aperture Labs Non-Sentient Devices"
#define WIFI_ACCESSPOINT_PASSCODE ""
#else
#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi pass here"
```

And then whatever changes need to be made to the cpp files to branch them based on #if USE_ACCESS_POINT_CONFIG or not. I won't be able to tinker around with the code for a while until an ESP32 gets here but skimming both portal_calender.ino and the examples for the WiFiManager it looks relatively straightforward. The WiFi Manager will block the init loop until successfully connected to a real wifi connection, though it would be handy if we could display a string with instructions (connect to access point, navigate to any webpage on device, get redirected to config page, enter credentials, etc.)

### PR DESCRIPTION
**Pull request by LordNed**
This is still a bit of a draft, still testing (and need to wait for my OpenWeatherMap API key to activate...)

This PR does a few things:
1) Use WiFiManager project by tapzu to allow configuring the Calendar via your phone/tablet.
2) Generates a QR code for easy configuration device connection (no need to type in manually connect your phone/tablet to the Calendar AP)
3) Enables OTA updates (theoretically)

This changes the user flow a little bit. When you first plug in the ESP32 it will place the ESP32 in Access Point mode for ten minutes. The screen will show a QR code which will automatically connect you to the access point.

IMG_20230223_Discord_21-55-54

Scanning the QR code will take you to a webpage that looks like this:
IMG_20230223_chrome_21-57-35
Going through "Configure WiFi" will take you to a page that lists all available Wi-Fi Access Points, and you can choose it and enter your password.

IMG_20230223_chrome_21-58-52

You can then set the other configuration settings, such as showing the month/day/etc. Additionally, once you have set the wifi SSID/Password and saved it, in the future you can use your desktop (and not a phone) to configure this screen, meaning you can copy/paste things from your web browser.

Once you hit Save, or the 10 minute timer expires, the ESP32 will exit Access Point mode and flow returns to normal (does an ntp sync, updates the screen, etc.). On subsequent wake-ups from deep sleep, the Access Point mode will be skipped (unless wi-fi is unavailable). If you press RESET on the back, it will reset the user-configuration flow and it will create an Access Point for ten minutes, but it will remember your credentials and settings.

This was the best balance I could strike between making user settings easy to get to, and preserving deep-sleep. I wanted to try a double-reset press detection (and only move into user config if you double pressed it) but I could not get that to work without putting code in loop() which is obviously a no-go. So now each time you replace the batteries it will spend 10 minutes with the AP on and then you won't see it again until you press reset or you next replace the batteries.  The proposed "is on USB power" check does not work with the Chinese ESP32 clone I have so it's questionable if that should ship anyways.

I don't have great tools for measuring power consumption, but on my Chinese ESP32 it draws ~130-150mA when the Access Point is up, and 9mA in deep sleep. The unmodified Portal Calendar sketch also runs at 9mA on this board, I don't have my Tindie one soldered in yet to compare on better hardware.

Configuration is saved as JSON to SPIFFS (and sent over Serial in debug mode, not including any wifi credentials). The configuration is loaded each time but only saved in certain scenarios (updating via web portal, updating your timezone, updating your lat/long)

Next Steps:
The WiFiManager Parameters could be spiced up to turn them into actual checkboxes instead of true/false. Perhaps we could do web-side validation of parameters, you can inject custom HTML, but HTML isn't my area of expertise. 
Need to finish testing the Weather portion of it. I tested the Calendar portion (Day of Week, Month, Year, TimeZone) and that works as expected. I dropped POSIX time from the UI for now (seemed like an advanced feature), but internally it still uses it and saves it in the config.
I had to drop some of the information from error screens, since currently the error reporting is using std::initializer_list and I would need dynamic strings to show things like the user-provided timezone now. I think it's okay given that it's easy to check the values (restart, go to web portal, etc.).

I will continue to test this but wanted to get the first draft looked at, especially now that other PRs are coming in that also rely on config systems, etc.

(P.S: I saw tonight @chrishoage 's double-boot detection for switching between Weather/Calendar. I like the idea but could also potential use that for getting into config mode instead of every-reset like I did)

### CODE REVIEW

**Comment by Apehaenger** [comment]
Hi LordNed!

Awesome add-on functionality!! Need to test it asap on my FireBeetle ;-)
Then I could also validate the (deep-sleep) current consumption if you've doubts in your measurement.

**Comment by LordNed** [comment]
I finished wiring up the Tindie ESP32 board and the draw at idle is basically nothing, < 0.01mA I believe, so this doesn't cause any regression in terms of power consumption. I think the only thing left is to update the readme. I'm a little confused about the commits @wuspy added here, I didn't know others could commit onto a PR - do I need to pull them to my local copy before I update the readme and then set this as Ready for Review?

**Comment by LordNed** [comment]
Also one thing that we now lack is some of the elaboration on config values. I didn't want to put them all on the Captive Portal config page (as it could get long). If you want to enable the Wiki for this Github project I'm happy to write out all the config options over there as to not lose that information.

**Comment by LordNed** [comment]
Updated to latest master (localization, hostname). I did change 
WiFi.setHostname to wifiManager.setHostname(HOSTNAME); to run through wifiManager. Tested by querying via command prompt's nslookup.

**Comment by wuspy** [comment]
> I'm a little confused about the commits @wuspy added here, I didn't know others could commit onto a PR - do I need to pull them to my local copy before I update the readme and then set this as Ready for Review?

Since I'm the repository owner I can commit onto PR branches. I just merged with master and update platformio.ini so I could start testing these changes. Sorry it's taken me so long to get around to this, I've busy with other stuff and when I did get back to this I wanted to address the easier PRs first.

> Also one thing that we now lack is some of the elaboration on config values. I didn't want to put them all on the Captive Portal config page (as it could get long). If you want to enable the Wiki for this Github project I'm happy to write out all the config options over there as to not lose that information.

WifiManager does have the ability to inject custom HTML/CSS/JS, so field descriptions could be styled in a way where they would look acceptable in the captive portal. It looks like it even has the ability to inject HTML for custom inputs like in [this example](https://github.com/tzapu/WiFiManager/blob/master/examples/Super/OnDemandConfigPortal/OnDemandConfigPortal.ino) so we don't need to use text inputs for boolean values or enum values, but I haven't actually tried that functionality so there may be caveats I'm not aware of. Since in my opinion the primary purpose of a wifi configuration feature like this is to make it so a calendar could be given away as a gift and then configured by someone who may not be tech-savvy enough to flash an ESP32, having instructions for how to set it up hosted on a github wiki rather than the UI of the device itself seems less than ideal. As is making them type in '1' to select an option instead of just using a dropdown.

>[Updated the README.md with OTA update instructions](https://github.com/wuspy/portal_calendar/pull/11/commits/ec4866f02293d68178e81d86f7dc1503387f18fa)

I'm hesitant to even mention OTA in the readme since that feature is likely to be disabled entirely. This PR + all the other stuff merged recently is using 96% of the ESP32's flash with the default partition table. I'm planning to switch to the huge_app partition table to buy an extra 2mb for future expansion, but that means going without an OTA partition. Again, the primary goal of this feature is to allow less tech-savvy users to configure the device and they're probably not going to be flashing firmware OTA. A secondary goal is to allow devs like you and me to change settings without flashing, meaning OTA becomes even less useful unless we're actively changing the code. Does WifiManager require OTA or can it function without? I'm assuming it can but I haven't checked.

**Comment by Apehaenger** [comment]
I love to see the work in this PR as I like the underlying idea to move the generic configuration (WiFi, Display content, ...) to the end-user/calendar- receiver.

But after @wuspy stated in another PR [comment](https://github.com/wuspy/portal_calendar/pull/10#issuecomment-1449247583), I also did a more detailed look to the WiFi Manager.
Well, I'm not such a sophisticated C/CPP developer as you are, and for sure I don't wanna blame here anyone, but I wasn't very impressed about some code i saw within the WiFi Manager. Beside @wuspy already noticed the mixture of HTML, CSS and JS, I noticed the injection stuff which look like the try/workaround the defined base structure.
However, it works, and for sure I'm not in the knowledge or position to blame anyone else work, but for me it looks (partly) complicated AND fragile!

So I did a quick look for alternatives, haven't found any and thought: "Take a look how the tasmota guys did it, may be they've another approach" ;-).

Well I didn't reached digging into the sources, but stumbled about another post (link follows).

So let me allow to throw in my 5 cent thought:
Instead of adding a possibly complicated (and probably also hungry) beast like the WiFi Manager on top of @wuspy 's portal_calendar, why not inverting the approach and add the portal_calendar on top of tasmota?

Here's the post [tasmota-custom-integration](https://github.com/phpcoder/tasmota-custom-integration) from which I got the thoughts.

Nuff said. If it's nonsense, simply drop a short "forget it", no detailed explanation required ;-)

**Comment by LordNed** [comment]
> Sorry it's taken me so long to get around to this, I've busy with other stuff and when I did get back to this I wanted to address the easier PRs first.
No worries, since it took me three weeks to getting around to writing the code anyways. :)

> It looks like it even has the ability to inject HTML for custom inputs like in [this example](https://github.com/tzapu/WiFiManager/blob/master/examples/Super/OnDemandConfigPortal/OnDemandConfigPortal.ino) so we don't need to use text inputs for boolean values or enum values... As is making them type in '1' to select an option instead of just using a dropdown.

Yeah there were a few examples, mostly centered around boolean fields. Web Development is outside my area of expertise so I figured better to check it in with the functionality (which is about equal to what there is now) and then someone could spice it up later.

> I'm hesitant to even mention OTA in the readme since that feature is likely to be disabled entirely. This PR + all the other stuff merged recently is using 96% of the ESP32's flash with the default partition table. I'm planning to switch to the huge_app partition table to buy an extra 2mb for future expansion, but that means going without an OTA partition

I'm fine with dropping OTA. I think it's neat, but given our storage space problems, I don't think it's worth it. I'd say we could drop the QR code support too, but I don't think it takes up much memory at all. I did some profiling (based on jumping between individual commits and compiling) and here's what I came up with:

```
Stock (No Weather, No WiFi Manager):
Sketch uses 868877 bytes (66%) of program storage space. Maximum is 1310720 bytes.
Global variables use 45116 bytes (13%) of dynamic memory, leaving 282564 bytes for local variables. Maximum is 327680 bytes.

WiFi Manager Added:
Sketch uses 1006809 bytes (76%) of program storage space. Maximum is 1310720 bytes.
Global variables use 47360 bytes (14%) of dynamic memory, leaving 280320 bytes for local variables. Maximum is 327680 bytes.

Weather Added:
Sketch uses 1137177 bytes (86%) of program storage space. Maximum is 1310720 bytes.
Global variables use 47416 bytes (14%) of dynamic memory, leaving 280264 bytes for local variables. Maximum is 327680 bytes.

QRCode Added:
Sketch uses 1137549 bytes (86%) of program storage space. Maximum is 1310720 bytes.
Global variables use 47416 bytes (14%) of dynamic memory, leaving 280264 bytes for local variables. Maximum is 327680 bytes.

SPIFFS/FS Added:
Sketch uses 1197097 bytes (91%) of program storage space. Maximum is 1310720 bytes.
Global variables use 47608 bytes (14%) of dynamic memory, leaving 280072 bytes for local variables. Maximum is 327680 bytes.

Creating the userConfig and converting classes to use it:
Sketch uses 1239513 bytes (94%) of program storage space. Maximum is 1310720 bytes.
Global variables use 48856 bytes (14%) of dynamic memory, leaving 278824 bytes for local variables. Maximum is 327680 bytes.

```
Base: 66%
Adding the WiFi Manager only adds an overhead of 10% to the program storage space, and 1% to global vars.
Adding Weather adds 11% of program space - less than I thought it would.
QRCode Generation: negligible
SPIFFS/FS: 5%
User Config Classes (added by this PR): 3%

I was surprised to find the stock install takes up so much space. I did some quick googling but didn't find any obvious answers on how to profile file-by-file where the storage space is going. If I had to hazard a guess, it's from the Chamber Icons (since there's more of those than there are weather icons). One thought I had, if it is the chamber/weather icons, is we could possibly compress them more? It looks like there's already some compression, but perhaps we could store them RLE encoded, or in tiles (since the border + empty space will repeat a lot). In general there's a lot of empty space and solid blacks which may make RLE viable. It looks like we're already actually drawing them to the screen pixel-by-pixel, so it might be relatively easy to switch that to decode the RLE as it draws?

I plugged a few of the image arrays into an online RLE encoder and get anywhere from a 20% size savings to a 10% loss, so you'd probably need to actually implement the RLE encoder for all assets first to measure the overall impact to see if it's actually a net gain or not.

> Does WifiManager require OTA or can it function without? I'm assuming it can but I haven't checked.
I don't know. It's not even mentioned in their documentation. The actual WiFi management part does I assume, but I'm not sure if the button will hang around as an errant leftover. You might be able to make a custom homepage or whatever and remove the button from the html.

> Well, I'm not such a sophisticated C/CPP developer as you are, and for sure I don't wanna blame here anyone, but I wasn't very impressed about some code i saw within the WiFi Manager. 

I agree, it's a bit iffy. But it also seems to be the thing people do, and there's something to be said for going where everyone else is - more support, more things you can google, hopefully less bugs, etc.

**Comment by wuspy** [comment]
>I was surprised to find the stock install takes up so much space. I did some quick googling but didn't find any obvious answers on how to profile file-by-file where the storage space is going. If I had to hazard a guess, it's from the Chamber Icons (since there's more of those than there are weather icons). One thought I had, if it is the chamber/weather icons, is we could possibly compress them more? It looks like there's already some compression, but perhaps we could store them RLE encoded, or in tiles (since the border + empty space will repeat a lot). In general there's a lot of empty space and solid blacks which may make RLE viable. It looks like we're already actually drawing them to the screen pixel-by-pixel, so it might be relatively easy to switch that to decode the RLE as it draws?

All the fonts and graphics are stored as raw 2bpp bitmaps embedded into the code. The biggest consumer of space among them is the 400px chamber number font which takes up 81k, about as much as the rest of the bitmaps combined. RLE would definitely improve that, but since we can gain an extra 2m by just changing the partition layout I don't consider optimizing the bitmap storage space a priority for now. If we really need OTA we could switch to the Minimal SPIFFS partition table which still buys an extra 700k of flash space. Or even create a custom partition table, although I'd be hesitant to do that because as far as I know that can only be done through PlatformIO and I want to maintain build compatibility between that and the Arduino IDE build system.

> I agree, it's a bit iffy. But it also seems to be the thing people do, and there's something to be said for going where everyone else is - more support, more things you can google, hopefully less bugs, etc.

I'm also not super impressed with WifiManager's code (or the 479 open issues) but like you said it is actively maintained and tons of people use it. But there's also [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer), which is quite popular and makes the server side code for this feature extremely simple. WifiManager doesn't use that and has its own web server implementation, but some of the smaller alternatives to it I've found on github do. A couple of those github projects even build their frontend as a separate webapp that's embedded into the firmware pre-gzipped, which not only gets the assets size down but also allows you to use things like typescript, scss, and nice frontend frameworks. Given that the main purpose of this project is still for me to have fun and learn stuff, I think I'll spend the next week or so experimenting with building this feature from scratch using ESPAsyncWebServer with a Sveltejs frontend. I've been wanting to try out Svelte for a while now anyway. If that doesn't work out I'll come back to this since WifiManager is still promising.

**Pull request closed without merging**
