### PR TITLE
WiFi Configuration

### LINKED ISSUE #7: Avoiding Hardcoding WiFi Credentials
Neat project. I'd like to give one as a gift but teaching friends how to compile and flash an ESP32 might be a bit too much of a gift. I was looking at potentially forking and integrating a wifi manager where, if wifi connection fails, it boots up into access point mode so you can connect to it via your phone and enter wifi credentials, and then have them saved on the device.

Looking around it looks like there's a package for the ESP32 by user Tzapu - https://github.com/tzapu/WiFiManager. Is this something you're interested in taking a pull request to add? If so, do you have thoughts on how you would want it implemented. I can make an effort to implement it that way to make it easier to take back as a PR.

My initial thoughts were to just set up a new set of defines in the header, instead of:

`#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi password here"`

Have something like
```
#define USE_ACCESS_POINT_CONFIG 1
#if USE_ACCESS_POINT_CONFIG
// IP Address the device will create a webserver on to config
#define WIFI_ACCESSPOINT_NAME "Aperture Labs Non-Sentient Devices"
#define WIFI_ACCESSPOINT_PASSCODE ""
#else
#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi pass here"
```

And then whatever changes need to be made to the cpp files to branch them based on #if USE_ACCESS_POINT_CONFIG or not. I won't be able to tinker around with the code for a while until an ESP32 gets here but skimming both portal_calender.ino and the examples for the WiFiManager it looks relatively straightforward. The WiFi Manager will block the init loop until successfully connected to a real wifi connection, though it would be handy if we could display a string with instructions (connect to access point, navigate to any webpage on device, get redirected to config page, enter credentials, etc.)

### PR DESCRIPTION
**Pull request by wuspy**
closes #7, closes #11

This purpose of this PR is to allow the calendar to be configured from a web interface rather than having to edit a configuration file and re-flash. @LordNed implemented a similar feature with #11 using an existing library, but in my opinion that library wasn't really a great fit. This implementation uses a custom Svelte app for the client, and [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer) for the server.

There's still a few details to work on, but overall I think it's complete enough to open a PR in case anyone wants to test it out or give feedback.

Although writing the web interface from scratch means localization of more than just the day and month names is now possible, this PR currently doesn't do that and the web interface just has strings hardcoded in English. Maybe after this is merged that can be something to work on, but this is still a small project and I'm not really sure it will have enough community support to maintain full localization in multiple languages.

### Todo

- [x] Add UI for connecting to insecure wifi networks
- [x] Expose setup app on the connected wifi network as well, if one is available. The app will need to know if its connected through AP or STA since they should not be able to change the wifi settings outside of AP mode. If a wifi network is already saved should the AP start by default when entering setup mode?
- [x] ~~Maybe add UI for connecting with a static IP? Is that even a use case for an IoT device?~~ **NOT PLANNED**
- [x] Better device instruction screens
- [x] Update documentation

### Screenshots

Screenshot_20230420-230706

Screenshot_20230420-230727

Screenshot_20230420-232429

Screenshot_20230420-230753

Screenshot_20230420-230759

### CODE REVIEW

**Comment by kluchrj** [comment]
I've been testing this out and it's been working well. The only hickup was during setup where I had to use the IP address because the hostname wouldn't resolve. It would be nice to show that on the display, but it's pretty easy to determine the IP regardless.

**Comment by wuspy** [comment]
> I've been testing this out and it's been working well. The only hickup was during setup where I had to use the IP address because the hostname wouldn't resolve. It would be nice to show that on the display, but it's pretty easy to determine the IP regardless.

Just to clarify this is without DEV_WEBSERVER right? When connected to its wifi, any hostname should resolve to the device's IP since the DNS entry is just "*".

**Comment by kluchrj** [comment]
> > I've been testing this out and it's been working well. The only hickup was during setup where I had to use the IP address because the hostname wouldn't resolve. It would be nice to show that on the display, but it's pretty easy to determine the IP regardless.
> 
> Just to clarify this is without DEV_WEBSERVER right? When connected to its wifi, any hostname should resolve to the device's IP since the DNS entry is just "*".

I realized I was using private DNS on my device which is why it wasn't resolving. Supporting that use case is up to you, I don't think it's very common.

**Comment by wuspy** [comment]
> > > I've been testing this out and it's been working well. The only hickup was during setup where I had to use the IP address because the hostname wouldn't resolve. It would be nice to show that on the display, but it's pretty easy to determine the IP regardless.
> > 
> > 
> > Just to clarify this is without DEV_WEBSERVER right? When connected to its wifi, any hostname should resolve to the device's IP since the DNS entry is just "*".
> 
> I realized I was using private DNS on my device which is why it wasn't resolving. Supporting that use case is up to you, I don't think it's very common.

Gotcha. I'm considering just using IP address for connecting to the setup page, especially after spending a couple days trying to get mDNS working over the connected wifi with mixed results. I can add a QR code link to the setup page on the display in addition to the one to connect to the access point so the URL really shouldn't matter for phone users at least.

I could also make the setup page a captive portal, I think I still have the code stashed to do that. But captive portal behavior is messy and not well standardized across devices, and every device says something like "Tap here to login to network" even though they're just going to the setup app for their calendar. I feel like that could just add confusion for the same users that an automatic captive portal is designed to benefit.

**Comment by knedl1k** [comment]
Is anyone working on anything right now, or what is the current status? Eventually, does anyone need help with anything in particular?

**Comment by wuspy** [comment]
> Is anyone working on anything right now, or what is the current status? Eventually, does anyone need help with anything in particular?

There's not much left to do, but I've also just been busy the past few months and haven't had time to work on it. The last major thing remaining is making a better looking instruction screen to show on the device for guiding the user through the connection process. Adding a footer to the web app might look nice too but that isn't critical.

I pushed the remaining changes I currently have, nothing major but it does add mDNS support over the connected wifi network as well as allowing a user to forget a saved network.

I do need to get this done pretty soon though as there's a couple friends I want to gift these to on christmas. If you have any ideas for how the device screen should look or for other things that should be changed, please do comment or open a PR!

**Pull request merged**
