### PR TITLE
Allow toggling between chamber and weather using GPIO0 (boot button)

### LINKED ISSUE #8: Hostname, SPI pins, and other improvments
I hacked on your project this weekend. 

I made the following improvements: 

1. Allow a hostname (I wanted something more recognizable in my network, I have a ton of ESP devices :sweat_smile:) 
2. Allow specifying SPI pins (when using HSPI on my ESP32S2 none of the pins are defined - and need to be manually defined)
3. Toggle between chamber and weather display using the GPIO 0 button (e.g. boot button) 

https://user-images.githubusercontent.com/1056886/220210141-7406e1ac-9b14-4275-9178-c0dba52aa30b.mp4

See the changes here in a comparison:

https://github.com/wuspy/portal_calendar/compare/master...chrishoage:portal_calendar:hoage/improvements

If you would like any of these to be upstream let me know! I'd be happy to cherry pick the commits to branches and open PRs. 

Thank you for your wonderful project :slightly_smiling_face: (sorry for opening an issue - github discussions don't seem to be enabled!)

### PR DESCRIPTION
**Pull request by chrishoage**
Video Example 

https://user-images.githubusercontent.com/1056886/220210141-7406e1ac-9b14-4275-9178-c0dba52aa30b.mp4

The intended use case is to change between Chamber Icons and Weather with out needing to hook up the ESP to a computer and recompile. 

In particular - where I live - the weather is only interesting a few months out of the year. The rest of the time I'd prefer the chamber icons :sweat_smile: 

This is predicated on a ESP having a boot button - but to my knowledge all recent ESP32s have this button, and it is addressable as GPIO0. 

The bulk of these changes are removing much of the `ifdef WEATHER` from the Display classes and replacing it with a boolean `showWeather`. 

The rest of the changes in the ino use a `RTC_DATA_ATTR` bool to keep the state of which should be shown. 

By default after a system reset weather is shown. After that the button can be used to toggle between the two. 

Some questions:

1. Should this be optional? Right now I have it turn on when weather is enabled. This can be optional - but at the cost of extra complexity. Is it harmful to just have this enabled? 
2. Should the wakeup pin be configurable? The BOM doesn't specify a push button, and adding one is complexity for a seldom used action (changing the display). Are there ESPs with out a GPIO0 (I was under the impression no) 

Closes https://github.com/wuspy/portal_calendar/issues/8

### CODE REVIEW

**Comment by wuspy** [comment]
So one thing I learned while trying out this feature is that I labeled the BOOT and RESET buttons backwards. Whoever designed the EzSBC board put buttons literally right next to IO0 and EN and then made them control the pins on the opposite side of the board. I was wondering why BOOT would reset this device but RESET wouldn't, and I guess now I finally have an answer on that. So I'll need to fix the error messages and the text on the cover STL, and I might just do that on this PR since I think it would make more sense to call the boot button 'MODE' after this feature is merged anyway.

But overall this feature has been working great. I do have a couple suggestions:

1. Your PR doesn't build without SHOW_WEATHER enabled. That definitely needs to be fixed.

2. I don't think those lines are necessary.

    ```cpp
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON);
    rtc_gpio_pullup_en(GPIO_NUM_0);
    rtc_gpio_pulldown_dis(GPIO_NUM_0);
    ```
    Any board with a button across IO0 should already have a builtin pullup resistor (the ezSBC has a 1k to 3.3v), and the `esp_sleep_enable_X_wakeup` functions set the pd_config automatically based on the wakeup sources. I've confirmed it still works on mine with these removed. I'm no ESP32 expert though so feel free to correct me if I'm wrong.

3. I'd like to prevent unnecessary wifi radio powerups on mode switching. Currently the actions performed on wakeup are just controlled by setting flags before going to sleep, and that's fine as long as the device doesn't have a reason to wakeup before its predetermined time. But now that the user can take actions that wake it arbitrarily I think a better way would be to store the timestamp that actions are schedule to happen, and then check those upon wakeup. There's no reason to do more than the 2 NTP syncs per day it already does, so those could just be scheduled for the amount of time its planning to sleep. But for weather it does make sense to refresh that if the current weather information is too outdated, so that could be scheduled for maybe an hour or so from the current time if they have the weather display active. The ESP32 won't wake up at that time without user action, it just lets it know to do a weather sync on wakeup if the current time is >= the scheduled time. I'm working on my own changes for how to handle this so don't feel obligated to spend your own time on it, but if you want to then go ahead and commit it because it's always possible that it could be better than whatever I write.

**Comment by wuspy** [comment]
> Should this be optional? Right now I have it turn on when weather is enabled. This can be optional - but at the cost of extra complexity. Is it harmful to just have this enabled?

I don't think so. If they don't want to use this feature then they just won't press the BOOT button. The code still needs to work with this enabled either way, so there's nothing gained by disabling it imo. And if I add calendar integration in the future that adds another screen they could toggle with this button.

> Should the wakeup pin be configurable? The BOM doesn't specify a push button, and adding one is complexity for a seldom used action (changing the display). Are there ESPs with out a GPIO0 (I was under the impression no)

The only 'officially' supported board for the time being is the EzSBC, and since that does have a button on IO0 that's all I really care about. When #11 or something like it gets merged, it's going to be checking USB power status using an EzSBC-specific technique, so supporting custom mode buttons on touch pins isn't really that much of a concern.

**Comment by chrishoage** [comment]
> Your PR doesn't build without SHOW_WEATHER enabled. That definitely needs to be fixed.

Whoops! Made a silly mistake this is now fixed. 

> I don't think those lines are necessary. [...] I've confirmed it still works on mine with these removed. I'm no ESP32 expert though so feel free to correct me if I'm wrong.

On my Sparkfun Think Plus ESP32S2 (I had laying around not used, and this seemed like a good project for it) I am getting a boot loop with out these lines (I just tried again today to verify) 

I was following this https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/system/sleep_modes.html#external-wakeup-ext1 (the esp32 docs are the same)

I'd be happy to but this behind a build flag (e.g. `ENABLE_RTC_GP0_PULLUP`) but if it's not harmful it might be simpler to leave it? 

I am also not an ESP expert so I'm kinda just trying stuff until it works. 

> but if you want to then go ahead and commit it because it's always possible that it could be better than whatever I write.

Just to make sure I'm attacking this from the same angle - we need to update the `Sleeping for 1st sync` else block in `setup`. 

I'm wondering if it would be possible to remove the `needsNtpSync` and `needsTimezoneSync` bools and instead rely entirely on `lastNtpSync`. 

- During wake up read `lastNtpSync`
- If no `lastNtpSync` sync 
- If `lastNtpSync` is inside of the drift range don't sync
- If `lastNtpSync` is inside of the drift rage but we're close to midnight (either before or after during one of the scheduled wake ups) sync

We might need to store the last wake up time in addition to the `lastNtpSync` time to make these comparisons. 

This would get rid of the bools on sleep and move all the logic to the start up, allowing a decision to be made if we need an ntp sync. 

Does this sound like what you were imagining? 

> I don't think so. If they don't want to use this feature then they just won't press the BOOT button. The code still needs to work with this enabled either way, so there's nothing gained by disabling it imo. And if I add calendar integration in the future that adds another screen they could toggle with this button.

This sounds good to me (and was my hope) 

> The only 'officially' supported board for the time being is the EzSBC, and since that does have a button on IO0 that's all I really care about.

Works for me!

**Comment by wuspy** [comment]
> I'd be happy to but this behind a build flag (e.g. ENABLE_RTC_GP0_PULLUP) but if it's not harmful it might be simpler to leave it?

Yeah it's fine, I was just trying to simplify the code and made some wrong assumptions.

> I'm wondering if it would be possible to remove the needsNtpSync and needsTimezoneSync bools and instead rely entirely on lastNtpSync.

I've tried out a few different ways to handle this, and I still think storing the scheduled action time and the actions to be performed at that time is the simplest way. The issue with getting rid of the action flags set before going to sleep is that not only do you have to determine how long you need to sleep for, but you now also need to determine what needs to be done when waking up which duplicates a lot of logic. I pushed a commit onto this branch if you wanna look it over, it'll probably be a few days before I merge this so I can test it out a bit more given the scope of the changes.

I also realized this PR would break the RTC correction, since that was done entirely in deepSleep and assumed it wouldn't wake up before the sleep duration completed. That should be fixed too.

**Comment by chrishoage** [comment]
> Yeah it's fine, I was just trying to simplify the code and made some wrong assumptions.

Okay, I'll leave it as is then. 

> I pushed a commit onto this branch if you wanna look it over, it'll probably be a few days before I merge this so I can test it out a bit more given the scope of the changes.

Everything looks good. One odd thing is I am getting a boot loop - but _only_ when monitoring. When I stop monitoring serial it settles. I'm guessing something is is up with monitoring triggering the GPIO0 during monitoring. I don't recall this behavior when I was testing this originally, but I don't really know enough about MCU programing to understand this change in behavior (e.g. it not being user error)

Just wanted to call this out. 

Otherwise this seems good to me. Is there anything you need from my end? 


```
❯ arduino-cli compile -b 'esp32:esp32:esp32s2' -p /dev/ttyUSB0 -u portal_calendar.ino
Sketch uses 1027446 bytes (78%) of program storage space. Maximum is 1310720 bytes.
Global variables use 41660 bytes (12%) of dynamic memory, leaving 286020 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.2.1
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-S2
Features: WiFi, No Embedded Flash, No Embedded PSRAM, ADC and temperature sensor calibration in BLK2 of efuse V2
Crystal is 40MHz
MAC: 7c:df:a1:55:0a:3a
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00004fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x0010bfff...
Compressed 14592 bytes to 10149...
Wrote 14592 bytes (10149 compressed) at 0x00001000 in 0.4 seconds (effective 328.5 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 428.2 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 568.1 kbit/s)...
Hash of data verified.
Compressed 1028576 bytes to 596089...
Wrote 1028576 bytes (596089 compressed) at 0x00010000 in 12.9 seconds (effective 639.8 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Used library     Version Path
WiFi             2.0.0   /home/chris/.arduino15/packages/esp32/hardware/esp32/2.0.6/libraries/WiFi
SPI              2.0.0   /home/chris/.arduino15/packages/esp32/hardware/esp32/2.0.6/libraries/SPI
ArduinoJson      6.20.0  /home/chris/Arduino/libraries/ArduinoJson
HTTPClient       2.0.0   /home/chris/.arduino15/packages/esp32/hardware/esp32/2.0.6/libraries/HTTPClient
WiFiClientSecure 2.0.0   /home/chris/.arduino15/packages/esp32/hardware/esp32/2.0.6/libraries/WiFiClientSecure

Used platform Version Path
esp32:esp32   2.0.6   /home/chris/.arduino15/packages/esp32/hardware/esp32/2.0.6


~/projects/portal_calendar hoage/chamber-weather-toggle* 21s
❯ arduino-cli monitor -p /dev/ttyUSB0 -b esp32:esp32:esp32s2 --config baudrate=115200
Monitor port settings:
baudrate=115200
Connected to /dev/ttyUSB0! Press CTRL-C to exit.
Request to timezoned.rop.nl request took 547ms
Response from timezoned.rop.nl: OK America/Los_Angeles PST8PDT,M3.2.0,M11.1.0
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Starting NTP request to pool.ntp.org
NTP sync timeout for server pool.ntp.org
Starting NTP request to time.google.com
NTP sync took 78ms
Looking up weather for 35.282753,-120.659615 from openweathermap
http://api.openweathermap.org/data/2.5/forecast?lat=35.282753&lon=-120.659615&units=imperial&appid=b1fcac0f9cc6861786d3e112bc15d1d8
Request to openweathermap took 518ms
Stopping WiFi
WiFi shutdown took 16ms
Updating display at 15-04-2023 09:16:18
Found 5 weather condition samples for 4/15/2023
Found 5 weather condition samples for 4/16/2023
Found 5 weather condition samples for 4/17/2023
Found 5 weather condition samples for 4/18/2023
Found 5 weather condition samples for 4/19/2023
Sleeping for 1st sync
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48699s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:22
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:22
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48695s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:26
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:26
Found 5 weather condition samples for 4/15/2023
Found 5 weather condition samples for 4/16/2023
Found 5 weather condition samples for 4/17/2023
Found 5 weather condition samples for 4/18/2023
Found 5 weather condition samples for 4/19/2023
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48692s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:29
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:29
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48688s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:33
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:33
Found 5 weather condition samples for 4/15/2023
Found 5 weather condition samples for 4/16/2023
Found 5 weather condition samples for 4/17/2023
Found 5 weather condition samples for 4/18/2023
Found 5 weather condition samples for 4/19/2023
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48685s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:37
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:37
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48681s, scheduled wakeup is 15-04-2023 22:48:01


ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x5 (DSLEEP),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x524
load:0x4004c000,len:0xa70
load:0x40050000,len:0x2914
entry 0x4004c18c
Setting system timezone to PST8PDT,M3.2.0,M11.1.0
Waking up at 15-04-2023 09:16:40
Wakeup cause: 3, Reset reason: 8
Toggling showWeather
Updating display at 15-04-2023 09:16:40
Found 5 weather condition samples for 4/15/2023
Found 5 weather condition samples for 4/16/2023
Found 5 weather condition samples for 4/17/2023
Found 5 weather condition samples for 4/18/2023
Found 5 weather condition samples for 4/19/2023
Wakeup is already scheduled
RTC correction for this sleep duration is 0s (factor 0.000000)
Sleeping for 48677s, scheduled wakeup is 15-04-2023 22:48:01
```

**Comment by wuspy** [comment]
That bootloop was because I accidentally removed this line, so the pullup on IO0 wasn't functional. I added it back.

```cpp
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON);
```

After doing a bit more reading on ESP32 sleep modes I decided to go ahead and make that pullup config optional since it could increase power usage and the EzSBC already has an external pullup on IO0. On my board I can't measure any meaningful difference in current between it being enabled or not, but boards using the S2 may be different.

Btw, your openweathermap API key is visible in that log so you might want to change it if you haven't done so already.

I don't think there's anything else I need you to do, I'll update the readme and get this merged. I do plan to open my own PR for wifi configuration in the next couple days if you wanna stick around to help test that out though.

**Comment by chrishoage** [comment]
> That bootloop was because I accidentally removed this line, so the pullup on IO0 wasn't functional. I added it back.

Gotcha - yes using the ENABLE_GPIO0_PULLUP flag to enable those pullups fixed the boot loop. 

> Btw, your openweathermap API key is visible in that log so you might want to change it if you haven't done so already.

Wow whoops! Revoked my old key. Thank you! 

> I do plan to open my own PR for wifi configuration in the next couple days if you wanna stick around to help test that out though.

Happy to help test. Just ping me when you need it. 

Thank you so much!

**Pull request merged**
